### ISSUE TITLE
error when I compile echo.c

### ISSUE THREAD

**Issue by orangejiejie** [payden/libwebsock#39]
when I compile echo.c, it show this error

root@ubuntu:/home/orange/libwebsock/examples# gcc -g -O2 -o echo echo.c -lwebsock
In file included from /usr/local/include/websock/websock.h:73:0,
                 from echo.c:17:
/usr/local/include/websock/utf.h:25:17: warning: inline function ‘decode’ declared but never defined
 uint32_t inline decode(uint32_t *state, uint32_t *codep, uint32_t byte);
                 ^
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libwebsock.so: undefined reference to `decode'
collect2: error: ld returned 1 exit status

**Comment by Zibri** [comment]
See https://github.com/payden/libwebsock/pull/40

**Comment by orangejiejie** [comment]
this issue can be closed
